### ISSUE TITLE
Version 0.0.z Task List

### ISSUE THREAD

**Issue by tay10r** [tay10r/libpx#1]
Here's a task list for everything that needs to get done for version 0.0.z
This version is meant to be the bare minimum feature set of a pixel art editor.

 - [ ] Transparent Background Checkerboard
 - [ ] Highlight Cursor Area
 - [ ] Proper Alpha Compositing
 - [ ] File Format
 - [x] Pen Tool
 - [x] Stroke Tool
 - [x] Bucket Tool
 - [ ] Rectangle Tool
 - [ ] Ellipse Tool
 - [ ] Color Picker Tool
